package dao;
// Generated Apr 24, 2024 12:08:52 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * City generated by hbm2java
 */
@Entity
@Table(name="city"
    ,catalog="hibernate_db"
)
public class City  implements java.io.Serializable {


     private Integer cityRef;
     private String cityName;
     private String cityDescription;
     private Set<Person> persons = new HashSet<Person>(0);

    public City() {
    }

	
    public City(String cityName, String cityDescription) {
        this.cityName = cityName;
        this.cityDescription = cityDescription;
    }
    public City(String cityName, String cityDescription, Set<Person> persons) {
       this.cityName = cityName;
       this.cityDescription = cityDescription;
       this.persons = persons;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="city_ref", unique=true, nullable=false)
    public Integer getCityRef() {
        return this.cityRef;
    }
    
    public void setCityRef(Integer cityRef) {
        this.cityRef = cityRef;
    }

    
    @Column(name="city_name", nullable=false, length=45)
    public String getCityName() {
        return this.cityName;
    }
    
    public void setCityName(String cityName) {
        this.cityName = cityName;
    }

    
    @Column(name="city_description", nullable=false)
    public String getCityDescription() {
        return this.cityDescription;
    }
    
    public void setCityDescription(String cityDescription) {
        this.cityDescription = cityDescription;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="city")
    public Set<Person> getPersons() {
        return this.persons;
    }
    
    public void setPersons(Set<Person> persons) {
        this.persons = persons;
    }




}


