package dao;
// Generated Apr 24, 2024 12:08:52 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Person generated by hbm2java
 */
@Entity
@Table(name="person"
    ,catalog="hibernate_db"
)
public class Person  implements java.io.Serializable {


     private Integer idPerson;
     private City city;
     private String personName;
     private String personLastname;
     private int personAge;

    public Person() {
    }

	
    public Person(String personName, String personLastname, int personAge) {
        this.personName = personName;
        this.personLastname = personLastname;
        this.personAge = personAge;
    }
    public Person(City city, String personName, String personLastname, int personAge) {
       this.city = city;
       this.personName = personName;
       this.personLastname = personLastname;
       this.personAge = personAge;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_person", unique=true, nullable=false)
    public Integer getIdPerson() {
        return this.idPerson;
    }
    
    public void setIdPerson(Integer idPerson) {
        this.idPerson = idPerson;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="city_ref")
    public City getCity() {
        return this.city;
    }
    
    public void setCity(City city) {
        this.city = city;
    }

    
    @Column(name="person_name", nullable=false, length=45)
    public String getPersonName() {
        return this.personName;
    }
    
    public void setPersonName(String personName) {
        this.personName = personName;
    }

    
    @Column(name="person_lastname", nullable=false, length=45)
    public String getPersonLastname() {
        return this.personLastname;
    }
    
    public void setPersonLastname(String personLastname) {
        this.personLastname = personLastname;
    }

    
    @Column(name="person_age", nullable=false)
    public int getPersonAge() {
        return this.personAge;
    }
    
    public void setPersonAge(int personAge) {
        this.personAge = personAge;
    }




}


